services:
  db:
    image: arm64v8/mariadb:latest
    container_name: notes-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: notes-be
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/notes
    volumes:
      - ./backend:/app
    working_dir: /app
    command: >
      sh -c "composer install &&
             if [ -d migrations ] && [ "$(ls -A migrations/*.php 2>/dev/null)" ]; then
               php bin/console doctrine:migrations:migrate --no-interaction;
             fi &&
             php -S 0.0.0.0:8000 -t public"

  frontend:
    build: ./frontend
    container_name: notes-fe
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command:  npm run dev

  adminer:
    image: arm64v8/adminer:latest
    container_name: notes-adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

volumes:
  db_data:
